import { cva } from "class-variance-authority"
import Image from "next/image"
import BadUIDesignImg from "@/images/bad-ui-showcase.png"
import { RoastUISystemSvg } from "../RoastUISystemSvg"
import { DrawnArrowSvg } from "../DrawnArrowSvg"
import { DrawnArrowVerticalSvg } from "../DrawnArrowVerticalSvg"
const container=cva("flex flex-col w-full max-w-screen-sm")
const topContainer=cva("flex flex-col items-center")
const middleContainer=cva("flex flex-col")
const bottomContainer=cva("flex gap-x-10")
const outputItem=cva("flex flex-col w-full ")
const outputLabel=cva("text-lg text-gray-200 font-semibold max-w-52 text-center flex flex-col")
const outputNumber = cva("text-gray-200 top-[50%-10px] right-[calc(50%-20px)] relative -translate-x-1/2 translate-y-1/4 text-sm font-semibold")

const arrow=cva("flex h-14 my-8",{
    variants:{
        size:{
            default:'h-15 my-8',
            small:'h-10 my-6',
        },
    },
    defaultVariants:{
        size:"default"
    }
})
const BadUIDesignImage=cva("w-72")
const label=cva("text-md text-gray-400 mt-4")
export function WorkFlow(){
    return (
        <div className={container()}>
            <div className={topContainer()}>
                <Image 
                src={BadUIDesignImg.src}
                width={BadUIDesignImg.width}
                height={BadUIDesignImg.height}
                alt="Bad UI Design"
                className={BadUIDesignImage()}
                />
                <span className={label()}>Your design</span>
            </div>
            <span className={arrow({size:'default'})} >
                <DrawnArrowVerticalSvg/>
            </span>
            <div className={middleContainer()}>
                <RoastUISystemSvg/>
            </div>
            <div className={bottomContainer()}>
                <div className={outputItem()}>
                    <span className={arrow({size:'small'})}><DrawnArrowVerticalSvg/>
                        <span className={outputNumber()}>1</span>
                    </span>
                    <p className={outputLabel()}>
                        Uncover UI/UX design mistakes❌/✅
                    </p>
                </div>
            <div className={outputItem()}>
                    <span className={arrow({size:'small'})}><DrawnArrowVerticalSvg/>
                    <span className={outputNumber()}>2</span>
                    </span>
                    <p className={outputLabel()}>
                        Improved UI/UX design generated by AI✨
                        <span className="text-sm text-gray-400 font-light">+ Source Code</span>
                    </p>
                </div>
            </div>
        </div>
    )
}